name: E2E Tests with CodeceptJS + Playwright

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run CodeceptJS tests (headless)
        env:
          HEADLESS: true
          CI: true   # ✅ ngăn không cho vào interactive shell
        run: npx codeceptjs run --grep "ai: test ai features" --plugins allure
